#!/bin/bash

source ~/software10d/autonomous-system/devel/setup.bash
source /etc/ros/env.sh
# export ROS_HOME=$(echo ~aeroless)/.ros
roslaunch can_sniffer can_sniffer.launch &
can_PID=$!
wait $can_PID
