#!/bin/bash

source ~/software10d/autonomous-system/devel/setup.bash
source /etc/ros/env.sh
source ~/catkin_build_ws/install/setup.bash --extend
# export ROS_HOME=$(echo ~aeroless)/.ros
rosrun launcher launcher &
launched_PID=$!
wait $launcher_PID
