#!/bin/bash

source ~/software10d/autonomous-system/devel/setup.bash
source /etc/ros/env.sh
# export ROS_HOME=$(echo ~aeroless)/.ros
roslaunch usb_cam usb_cam.launch &
usb_cam_PID=$!
wait $usb_cam_PID
