#!/bin/bash

source ~/software10d/autonomous-system/devel/setup.bash
source /etc/ros/env.sh
# export ROS_HOME=$(echo ~aeroless)/.ros
roslaunch watchdog watchdog.launch &
watchdog_PID=$!
wait $watchdog_PID
